/*------this is auto generated by build engine, it is for native Feature/Default Value build config, Please do not modify manually------*/
#ifndef _SPR_TARGET_H_
#define _SPR_TARGET_H_


#define MODULES_PROJECT_CUSTOMER_NAME    "Micromax"
#define MODULES_PROJECT_CUSTOMER_SKU    "Micromax_India"
#define MODULES_PROJECT_NAME    "PD6511M_64"
#define BUILD_RO_BUILD_DISPLAY_ID    "MMX_E7533_SW_V03_HW_V2.0_20210211"
#define BUILD_HARDWARE_VERSION    "V2.0"
#define BUILD_RO_PRODUCT_MODEL    "Micromax E7533"
#define NATIVE_DISPLAY_NAME_BT_PRODUCT    "IN1b"
#define NATIVE_DISPLAY_NAME_CAMERA_VENDOR    "Micromax"
#define NATIVE_DISPLAY_NAME_CAMERA_MODEL    "IN1b"
#define NATIVE_DISPLAY_NAME_GADGET_VENDOR    "IN1b"
#define NATIVE_DISPLAY_NAME_GADGET_PRODUCT    "IN1b"
#define NATIVE_DISPLAY_NAME_MTP_VENDOR    ""
#define NATIVE_DISPLAY_NAME_MTP_PRODUCT    "IN1b"
#define SPR_COUNTRY_CODE_FEATURE_NATIVE_UNDEFINED    

#endif